# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfabae32d12cae8a42bda62a695c255b3e1bc137db893562c40024c0386e6562442403edb6677e32aec643ceb63da15678f5f559270516fb28bc8715adef25ca

test:
  secret_key_base: 865f1589c9953f6c0f5d898dd80af1d08009e769f9189d1e15191dbebd9dece6e535d1ba7563294303150ec39aafada155a657178e2bc1298f8a43c3b6cf35bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
